server:
  port: 0

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

jwt:
  private-key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC8Emu6OXU1JoOo
    ik2TFsE1PuHWqJQpktd0bGnaha14U/Aexyb0OALotB/SEnPNxxhQqz2eKVnp6hYN
    EjC1TDZzB/NtKJQVdIk2qlrSbvHiAXZnRLfAfxuTIVbXQcqpLWJMvQpaALjg2zfd
    Y5VPIRDtO9aBmctQL11tVvXkql8gdT+TD5jYO4ZpfjV9am0nbehyEc37E85A/wHM
    rATbvS8NPh+X6bWTxxHQEFRcs4zxgCr09SSrnaG3FGjezC2RI8vom33QqEMxYMiT
    xotDJ6BglmpS7kc6TknBubfwO2wpuejsS7JJalJhV0IdQ5jWzdQzU440cBYzguI1
    3rBPuEkpAgMBAAECggEAKhHkzy9zLISFBvqJB9IbPhHm6uGi4vnaAE0QELW+bCA6
    omfiKtcsr2k7hP5jsTBMHB9yFSMi3dRjQmFDTArUUz8AEPb2ySXcW8IXtuLicK/r
    EIaqpADK5kqa5mPtNZLVXl0bJ67prELdaESSbbTz2F1+Sldgx3sQ5xiAwLnrtZKi
    g0F86nN90CTOFBOv6N/y6WX2q4dP9Z6iwyIvrR5HygI1euBMaZhbZd8UzG+J5CH+
    d1yoOJgAPiNQi2von2R/7ezpCfJqV8vk+FWfMoMJxcatnjYbtHpaei7GkCUaiZJF
    EmXhawShxo403BxSIzetp+v4hX36v4kEXEM5SacSUQKBgQDiTBWSKfDWKKDVdQGM
    pDvCJ++0GaNdMiO6w/YoYF1f/gKITiM5iNwCceRz/e4JmN/bf2kPeCPYm75yqJ7o
    ZdpGqHTC0JYObdi15Mynv4Lby6vOJfW2pACFq77lv+5xWBbS1jHCu7ab4lWcWtyB
    +ByTUY2R7z3zUQPy09wO7iXC1wKBgQDUwembvdx171+/A2tkTzricRgcgkTdPULt
    mGAJVnWWDpG5kMgaf8OB8+LoD+ey63PpCRXnbXKBrsv2GBBIHW/zJuu5sW373gkS
    ijCW4vMich+RH7RJttFhqG7mC37gKMuxWd/BBI0AjR3OpqbStFTlhnN8I9Vw81Vy
    MH5yfxzT/wKBgQCAPkXrM0F83EFpNonOPjRvb1p0YiMmaYe+C9ewQgwonjapMD7e
    GCU2bXzeDwWbAru6FJZhYeBOnNRs/gowAaiValnhHXwsaSvqyOMCHZH3JZETnoeF
    HaP+HLpuUTq7mQQ2L5S7ms19weJqXUOhlA39nrXwAfjFrx/huRZ4j5VuuQKBgGm/
    UBuGzNMZfV91laUv9Daku7U/0nacgm2RtPovLRa+exPesHbrVgN7cyag8Sru+Je1
    WlvC/I0Ukm/pGf6eEwyqJbQQSnhLrfq3ENuORgay7pm1Rmj1IzEFBMn2oMNNw6CM
    6TgIyQSjH1OdZYGI/EFxCGmFbgtMBwZQsCi8oVmFAoGAdYCet82vnTlVggMhbuW+
    CYUABcBBkvd5n4T+6y4kEjn7I3R9yd9fL2MYpA5A68NZUZoJehGrvKVi4Rhg5WGN
    AV1ke8DH3t2j4DviyM6rknKzeeMEfAvq+YEYD/ZtLAoN5ft5OjMjCPZ194Xh0GrF
    0fyoKzygSvEpFqnKAqqdYso=
    -----END PRIVATE KEY-----
  public-key: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvBJrujl1NSaDqIpNkxbB
    NT7h1qiUKZLXdGxp2oWteFPwHscm9DgC6LQf0hJzzccYUKs9nilZ6eoWDRIwtUw2
    cwfzbSiUFXSJNqpa0m7x4gF2Z0S3wH8bkyFW10HKqS1iTL0KWgC44Ns33WOVTyEQ
    7TvWgZnLUC9dbVb15KpfIHU/kw+Y2DuGaX41fWptJ23ochHN+xPOQP8BzKwE270v
    DT4fl+m1k8cR0BBUXLOM8YAq9PUkq52htxRo3swtkSPL6Jt90KhDMWDIk8aLQyeg
    YJZqUu5HOk5Jwbm38DtsKbno7EuySWpSYVdCHUOY1s3UM1OONHAWM4LiNd6wT7hJ
    KQIDAQAB
    -----END PUBLIC KEY-----
  issuer: auth-service
  audience: api-gateway
  access-token-expiry: 900
  refresh-token-expiry: 604800

logging:
  level:
    root: INFO
    prashant.auth_service: DEBUG
    org.springframework.security: DEBUG